# Generated by Django 5.2 on 2025-06-21 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0006_vacation'),
        ('teachers', '0020_remove_reschedule_status_reschedule_offline_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='room',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='routine.room'),
        ),
    ]
