# Generated by Django 5.2.1 on 2025-06-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0021_alter_classschedule_room'),
        ('teachers', '0025_reschedule_new_schedule_and_more'),
    ]

    operations = [
    ]
