<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-29 16:05
=======
# Generated by Django 5.2 on 2025-04-29 16:51
>>>>>>> 46f368cd4c00a67b4b5c65de788ca0f7533721c8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
