# Generated by Django 5.2 on 2025-05-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_slot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='semester',
            field=models.CharField(default='3-2', max_length=20),
        ),
    ]
