# Generated by Django 5.2 on 2025-05-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_routine_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='semester',
            field=models.CharField(choices=[('1-1', '1st Year 1st Semester'), ('1-2', '1st Year 2nd Semester'), ('2-1', '2nd Year 1st Semester'), ('2-2', '2nd Year 2nd Semester'), ('3-1', '3rd Year 1st Semester'), ('3-2', '3rd Year 2nd Semester'), ('4-1', '4th Year 1st Semester'), ('4-2', '4th Year 2nd Semester')], max_length=10),
        ),
    ]
