# Generated by Django 5.2 on 2025-05-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0005_alter_routine_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='semester',
        ),
        migrations.AddField(
            model_name='routine',
            name='batch',
            field=models.CharField(default='3-2', max_length=10),
        ),
    ]
