# Generated by Django 5.2 on 2025-05-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_academiccalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
